//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopTenMovies.API.GenreService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GenreService.IGenreService")]
    public interface IGenreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenreService/GetGenres", ReplyAction="http://tempuri.org/IGenreService/GetGenresResponse")]
        TopTenMovies.Entities.Genre[] GetGenres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenreService/GetGenres", ReplyAction="http://tempuri.org/IGenreService/GetGenresResponse")]
        System.Threading.Tasks.Task<TopTenMovies.Entities.Genre[]> GetGenresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGenreServiceChannel : TopTenMovies.API.GenreService.IGenreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenreServiceClient : System.ServiceModel.ClientBase<TopTenMovies.API.GenreService.IGenreService>, TopTenMovies.API.GenreService.IGenreService {
        
        public GenreServiceClient() {
        }
        
        public GenreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TopTenMovies.Entities.Genre[] GetGenres() {
            return base.Channel.GetGenres();
        }
        
        public System.Threading.Tasks.Task<TopTenMovies.Entities.Genre[]> GetGenresAsync() {
            return base.Channel.GetGenresAsync();
        }
    }
}
